project_id = "idvsrsbvulyefsqdgjwg"

[functions.get-weather]
verify_jwt = false

[functions.farm-chat]
verify_jwt = false

[functions.reset-phone-password]
verify_jwt = false

[functions.scheme-eligibility]
verify_jwt = false